### ISSUE TITLE
Would it be possible...

### ISSUE THREAD

**Issue by aastratinei** [NikitaBazhenov/UbersichtWunderlistTasks#3]
Hi! Would it be possible to somehow show only a certain number of tasks from a specific list? Like if I have 50 tasks in one list, could I just show 5 of them?

**Comment by NikitaBazhenov** [comment]
Hi, I added this functionality, please update widget file.
Usage example:

```
 iNumbers: 
   'ListsName': 2
   'Products': 1
```
